[mgr]
show_hidden = true

[opener]
edit = [
  { run = "nvim -- %s", block = true, for = "unix" },
]
open = [
  { run = "open -- %s", for = "unix" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { url = "*", use = "open" },
]
