general.import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0
normal = { family = "RobotoMono Nerd Font", style = "Regular" }

[window]
opacity = 0.94
blur = true

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 8
y = 8
